"""
Sub-pattern definitions for each vulnerability cluster.
Each cluster has 5-8 distinct sub-patterns that represent
genuinely different bugs within the same category.
"""

CLUSTER_SUBPATTERNS = {
    "oracle-dependency": [
        {"name": "stale_price", "difficulty": "beginner", "desc": "Oracle returns stale data because there is no check on updatedAt or round completeness. Contract uses old price for financial decisions."},
        {"name": "zero_negative_price", "difficulty": "beginner", "desc": "Oracle returns zero or negative price (malfunction/depeg). Contract does not validate price > 0 before using it. Unsafe int256 to uint256 cast."},
        {"name": "wrong_decimals", "difficulty": "intermediate", "desc": "Chainlink returns 8-decimal prices but contract assumes 18 decimals (or vice versa). Math is off by 1e10, causing massive over/under-valuation."},
        {"name": "spot_price_manipulation", "difficulty": "intermediate", "desc": "Contract reads price from an AMM pool (getReserves/balanceOf ratio) instead of a proper oracle. Attacker manipulates with flash loan."},
        {"name": "no_fallback_oracle", "difficulty": "intermediate", "desc": "Single oracle source with no fallback. When primary oracle reverts (Chainlink multisig freeze, sequencer down), entire protocol freezes."},
        {"name": "twap_too_short", "difficulty": "advanced", "desc": "TWAP oracle uses too short a window (e.g., 1 block or 30 seconds). Attacker can manipulate across multiple blocks cheaply."},
        {"name": "sequencer_uptime", "difficulty": "advanced", "desc": "L2 deployment uses Chainlink but does not check L2 sequencer uptime feed. After sequencer comes back up, stale prices are used before oracles update."},
        {"name": "multi_oracle_inconsistency", "difficulty": "advanced", "desc": "Protocol uses two oracle sources that can diverge. No reconciliation logic — attacker exploits the higher/lower price depending on operation."},
    ],
    "reentrancy": [
        {"name": "classic_eth_reentrancy", "difficulty": "beginner", "desc": "ETH transfer via call{value} before state update. Attacker re-enters withdraw to drain funds. Classic CEI violation."},
        {"name": "erc721_callback", "difficulty": "beginner", "desc": "safeTransferFrom triggers onERC721Received callback. State is not finalized before the transfer, allowing re-entry."},
        {"name": "cross_function", "difficulty": "intermediate", "desc": "Function A makes external call, attacker re-enters through Function B which reads stale state that A hasn't updated yet."},
        {"name": "read_only_reentrancy", "difficulty": "intermediate", "desc": "View function reads state during a callback from another protocol. The state is mid-update, returning incorrect values used by a third contract."},
        {"name": "erc777_hooks", "difficulty": "intermediate", "desc": "ERC777 tokensReceived/tokensToSend hooks give sender/receiver execution during transfer. Contract assumes ERC20 behavior."},
        {"name": "cross_contract", "difficulty": "advanced", "desc": "Contract A calls Contract B, which calls back to Contract A (or Contract C that reads A's state). State is inconsistent across the call chain."},
        {"name": "reentrancy_guard_bypass", "difficulty": "advanced", "desc": "ReentrancyGuard protects one function but not another that shares the same state. Attacker enters through unprotected function."},
        {"name": "balancer_vault_reentrancy", "difficulty": "advanced", "desc": "Protocol integrates with a DeFi primitive (like Balancer) whose callback can be exploited to re-enter with manipulated pool state."},
    ],
    "access-control": [
        {"name": "missing_modifier", "difficulty": "beginner", "desc": "Critical function (mint, pause, setFee) has no access control modifier. Anyone can call it."},
        {"name": "wrong_role_check", "difficulty": "beginner", "desc": "Function checks for wrong role (checks admin when it should check operator, or uses OR instead of AND for role combination)."},
        {"name": "unprotected_initializer", "difficulty": "beginner", "desc": "Initialize function can be called by anyone, allowing attacker to set themselves as admin on a proxy deployment."},
        {"name": "tx_origin", "difficulty": "intermediate", "desc": "Uses tx.origin instead of msg.sender for authorization. Phishing attack through a malicious contract forwards the real user's tx.origin."},
        {"name": "delegatecall_context", "difficulty": "intermediate", "desc": "Function checks msg.sender but is called via delegatecall where msg.sender is preserved from the proxy context, bypassing the check."},
        {"name": "two_step_ownership_missing", "difficulty": "intermediate", "desc": "transferOwnership in one step. If wrong address is passed, ownership is permanently lost with no recovery."},
        {"name": "privilege_escalation", "difficulty": "advanced", "desc": "Role hierarchy allows a lower-privilege role to grant itself higher privileges through a chain of permitted operations."},
        {"name": "timelock_bypass", "difficulty": "advanced", "desc": "Governance timelock can be bypassed through an emergency function or by manipulating the queue/execute flow."},
    ],
    "vault-share-accounting": [
        {"name": "first_depositor_inflation", "difficulty": "beginner", "desc": "First depositor mints 1 share, donates tokens directly to vault. Share price inflates, next depositor gets 0 shares from rounding."},
        {"name": "donation_attack", "difficulty": "beginner", "desc": "totalAssets reads balanceOf, which includes externally donated tokens. Attacker donates to manipulate share price."},
        {"name": "fee_desync", "difficulty": "intermediate", "desc": "Deposit/withdrawal fees are deducted from assets but shares are calculated against pre-fee amounts. Over time, share backing drifts."},
        {"name": "reward_accounting_gap", "difficulty": "intermediate", "desc": "Rewards accrue while totalStaked is zero. First depositor captures all accumulated rewards with a tiny stake."},
        {"name": "rounding_direction", "difficulty": "intermediate", "desc": "Rounding favors the user instead of the protocol. On deposit, shares round UP; on withdraw, assets round UP. Protocol slowly leaks value."},
        {"name": "virtual_price_manipulation", "difficulty": "advanced", "desc": "Virtual shares/assets offset is too small relative to expected deposits, or is not applied consistently across all operations."},
        {"name": "withdraw_queue_desync", "difficulty": "advanced", "desc": "Pending withdrawals are counted in totalAssets but the tokens are locked. New depositors get inflated share value."},
        {"name": "flash_deposit_withdraw", "difficulty": "advanced", "desc": "Deposit and withdraw in same transaction captures a share of pending rewards or yield without being exposed to risk."},
    ],
    "arithmetic-precision": [
        {"name": "division_before_multiplication", "difficulty": "beginner", "desc": "Division happens before multiplication, causing precision loss. (a / b) * c loses more precision than (a * c) / b."},
        {"name": "rounding_to_zero", "difficulty": "beginner", "desc": "Integer division of small numerator by large denominator always rounds to zero. Small users get nothing."},
        {"name": "accumulator_dust", "difficulty": "intermediate", "desc": "Rounding errors accumulate over many iterations. Each individual error is tiny but compounds to significant value over time."},
        {"name": "phantom_overflow", "difficulty": "intermediate", "desc": "Intermediate multiplication overflows even though the final result fits. (a * b) / c where a*b exceeds uint256."},
        {"name": "decimal_mismatch", "difficulty": "intermediate", "desc": "Mixing tokens with different decimals (USDC 6 vs WETH 18) without proper scaling. Math is off by orders of magnitude."},
        {"name": "percentage_rounding", "difficulty": "advanced", "desc": "Fee/reward percentages use basis points but rounding direction is wrong. Over millions of operations, significant funds leak."},
        {"name": "fixed_point_truncation", "difficulty": "advanced", "desc": "Fixed-point math library (WAD/RAY) used incorrectly. Mixing scaled and unscaled values in the same expression."},
        {"name": "price_per_share_manipulation", "difficulty": "advanced", "desc": "pricePerShare calculation loses precision at extreme values (very large totalSupply, very small totalAssets or vice versa)."},
    ],
    "denial-of-service": [
        {"name": "push_refund_dos", "difficulty": "beginner", "desc": "Push-based refund pattern. Recipient contract reverts on ETH receive, blocking the entire function for all users."},
        {"name": "unbounded_loop", "difficulty": "beginner", "desc": "Loop iterates over user-growable array. Attacker adds enough entries that the function exceeds block gas limit."},
        {"name": "external_call_revert", "difficulty": "beginner", "desc": "Function calls external contract that can revert. No try/catch, so one bad actor blocks the whole batch."},
        {"name": "token_blacklist_dos", "difficulty": "intermediate", "desc": "USDC/USDT blacklist blocks transfer to/from an address. If a protocol address gets blacklisted, funds are stuck."},
        {"name": "dust_amount_dos", "difficulty": "intermediate", "desc": "Attacker sends tiny amounts to create many entries in a mapping/array, inflating gas costs for legitimate operations."},
        {"name": "block_stuffing", "difficulty": "intermediate", "desc": "Time-sensitive operation (auction end, oracle update) can be delayed by filling blocks with high-gas transactions."},
        {"name": "selfdestruct_dos", "difficulty": "advanced", "desc": "Contract logic depends on address(this).balance being zero or a specific value. Attacker forces ETH via selfdestruct."},
        {"name": "storage_collision_dos", "difficulty": "advanced", "desc": "Mapping key collision or storage slot overlap causes one user's operation to corrupt another's state."},
    ],
    "initialization": [
        {"name": "missing_initializer_modifier", "difficulty": "beginner", "desc": "Upgradeable contract's initialize() function lacks the initializer modifier. Can be called multiple times by anyone."},
        {"name": "constructor_vs_initializer", "difficulty": "beginner", "desc": "Logic is in constructor instead of initializer for a proxy-deployed contract. Constructor runs on implementation, not proxy."},
        {"name": "disable_initializers_missing", "difficulty": "beginner", "desc": "Implementation contract doesn't call _disableInitializers() in constructor. Attacker can initialize the implementation directly."},
        {"name": "reinitializer_version_skip", "difficulty": "intermediate", "desc": "Using reinitializer(N) but skipping version numbers. An upgrade path skips a version, leaving state partially initialized."},
        {"name": "initialization_front_running", "difficulty": "intermediate", "desc": "No access control on initialize(). Between deployment and initialization, attacker front-runs to become admin."},
        {"name": "partial_initialization", "difficulty": "intermediate", "desc": "Initialize sets some state but misses critical parameters. Protocol operates with zero/default values for important configs."},
        {"name": "double_init_via_delegatecall", "difficulty": "advanced", "desc": "Proxy initialized, but implementation can still be initialized via direct call. Attacker initializes implementation, then exploits via delegatecall path."},
        {"name": "init_order_dependency", "difficulty": "advanced", "desc": "Multiple contracts must be initialized in specific order. If order is wrong, cross-references point to zero addresses."},
    ],
    "proxy-upgrade": [
        {"name": "storage_collision", "difficulty": "beginner", "desc": "New implementation reorders or inserts storage variables, causing existing data to be read from wrong slots."},
        {"name": "missing_gap", "difficulty": "beginner", "desc": "Base contract doesn't reserve storage gap (__gap). Derived contracts collide with base when base is upgraded."},
        {"name": "function_selector_clash", "difficulty": "intermediate", "desc": "Proxy admin function selector collides with an implementation function. Calls intended for implementation go to proxy instead."},
        {"name": "uups_no_upgrade_check", "difficulty": "intermediate", "desc": "UUPS implementation doesn't override _authorizeUpgrade or has weak auth. Anyone can upgrade to malicious implementation."},
        {"name": "immutable_in_proxy", "difficulty": "intermediate", "desc": "Implementation uses immutable variables set in constructor. Proxy doesn't have these values (they're in implementation's bytecode)."},
        {"name": "delegatecall_to_selfdestruct", "difficulty": "advanced", "desc": "Delegatecall target contains selfdestruct. When called via delegatecall, the proxy contract is destroyed."},
        {"name": "transparent_admin_collision", "difficulty": "advanced", "desc": "TransparentProxy admin calls go to proxy, non-admin calls to implementation. But admin address check has edge cases."},
        {"name": "beacon_upgrade_race", "difficulty": "advanced", "desc": "Multiple proxies share a beacon. Upgrading the beacon atomically changes all proxies, but some may be mid-transaction."},
    ],
    "signature-auth": [
        {"name": "missing_nonce", "difficulty": "beginner", "desc": "Signed message has no nonce. Same signature can be replayed multiple times."},
        {"name": "ecrecover_zero_check", "difficulty": "beginner", "desc": "ecrecover returns address(0) for invalid signatures. No check for recovered == address(0), so invalid sigs pass as 'authorized by zero address'."},
        {"name": "cross_chain_replay", "difficulty": "intermediate", "desc": "EIP-712 domain separator doesn't include chainId, or chainId is hardcoded. Signature valid on one chain replays on another."},
        {"name": "signature_malleability", "difficulty": "intermediate", "desc": "ECDSA signature has two valid (s, v) values. If both are accepted, signature uniqueness is broken, enabling replay."},
        {"name": "permit_frontrun", "difficulty": "intermediate", "desc": "ERC20 permit() call can be front-run. Attacker sees permit in mempool, calls it first, then the original tx reverts."},
        {"name": "deadline_missing", "difficulty": "advanced", "desc": "Signed message has no expiration/deadline. Signature captured today is valid forever, even after intended use."},
        {"name": "struct_hash_collision", "difficulty": "advanced", "desc": "Two different struct types produce the same EIP-712 typeHash due to similar field names. Cross-type signature forgery."},
        {"name": "bitmap_nonce_overflow", "difficulty": "advanced", "desc": "Bitmap-based nonce tracking has limited space. After enough signatures, nonce slots wrap around and old signatures become replayable."},
    ],
    "integer-overflow": [
        {"name": "unchecked_overflow", "difficulty": "beginner", "desc": "Arithmetic in unchecked block overflows silently. Developer used unchecked for gas savings but the values can exceed uint256."},
        {"name": "unsafe_downcast", "difficulty": "beginner", "desc": "uint256 value cast to uint128/uint96/uint64. If value exceeds the smaller type's max, it truncates silently."},
        {"name": "negative_underflow", "difficulty": "beginner", "desc": "Subtraction underflows to uint256 max. Balance check happens after the subtraction, not before."},
        {"name": "multiplication_overflow", "difficulty": "intermediate", "desc": "Two large uint256 values multiplied. Even with Solidity 0.8 checks, the revert breaks core functionality."},
        {"name": "signed_unsigned_mismatch", "difficulty": "intermediate", "desc": "Mixing int256 and uint256 in calculations. Negative int256 cast to uint256 wraps to huge positive number."},
        {"name": "timestamp_cast", "difficulty": "intermediate", "desc": "block.timestamp (uint256) cast to smaller type for storage. Timestamps near 2^32 overflow in year 2106."},
        {"name": "accumulator_overflow", "difficulty": "advanced", "desc": "Accumulator variable (total rewards, total fees) grows unboundedly. Eventually overflows after long protocol operation."},
        {"name": "bit_shift_overflow", "difficulty": "advanced", "desc": "Left shift by variable amount. If shift >= 256, result is zero in Solidity (not an overflow error)."},
    ],
    "flash-loan-attacks": [
        {"name": "governance_flash_loan", "difficulty": "beginner", "desc": "Governance voting power is based on current token balance. Flash loan tokens, vote, return in same transaction."},
        {"name": "oracle_manipulation_via_flash", "difficulty": "intermediate", "desc": "Flash loan large amount, manipulate AMM pool price, use manipulated price in victim protocol, profit."},
        {"name": "collateral_inflation", "difficulty": "intermediate", "desc": "Flash loan assets, deposit as collateral, borrow against inflated position, repay flash loan. Undercollateralized loan remains."},
        {"name": "fee_extraction", "difficulty": "intermediate", "desc": "Flash loan to inflate a fee pool temporarily. Claim disproportionate share of fees, then withdraw."},
        {"name": "sandwich_liquidation", "difficulty": "advanced", "desc": "Flash loan to manipulate price, trigger liquidation of healthy position, profit from discounted liquidation collateral."},
    ],
    "frontrunning-mev": [
        {"name": "no_slippage_protection", "difficulty": "beginner", "desc": "Swap with slippage tolerance set to 0 or very high. Sandwich bot extracts value by front-running and back-running."},
        {"name": "commit_reveal_missing", "difficulty": "intermediate", "desc": "Action reveals information in mempool (bid amount, NFT mint ID). No commit-reveal pattern, so front-runner copies."},
        {"name": "oracle_update_frontrun", "difficulty": "intermediate", "desc": "Oracle update transaction visible in mempool. Attacker front-runs with position based on upcoming price change."},
        {"name": "first_come_first_serve", "difficulty": "intermediate", "desc": "Protocol has a 'first to claim' reward. Bots monitor for the condition and front-run legitimate claimers."},
        {"name": "timestamp_dependence", "difficulty": "advanced", "desc": "Contract logic depends on block.timestamp for randomness or deadlines. Miner/validator can manipulate within bounds."},
    ],
    "lending-liquidation": [
        {"name": "health_factor_manipulation", "difficulty": "beginner", "desc": "Health factor check uses spot price that can be manipulated. Attacker makes a healthy position appear liquidatable."},
        {"name": "liquidation_threshold_bypass", "difficulty": "intermediate", "desc": "Rounding in health factor calculation allows positions slightly below threshold to avoid liquidation."},
        {"name": "bad_debt_accumulation", "difficulty": "intermediate", "desc": "No mechanism to handle positions that are undercollateralized beyond liquidation incentive. Bad debt socializes."},
        {"name": "interest_rate_manipulation", "difficulty": "intermediate", "desc": "Utilization-based interest rate can be spiked by flash-borrowing most available liquidity."},
        {"name": "liquidation_cascade", "difficulty": "advanced", "desc": "Liquidating one position dumps collateral, crashing price, making more positions liquidatable in a cascade."},
    ],
    "bridge-cross-chain": [
        {"name": "message_replay", "difficulty": "beginner", "desc": "Cross-chain message has no nonce or replay protection. Same message can be executed multiple times on destination."},
        {"name": "chain_id_missing", "difficulty": "intermediate", "desc": "Message doesn't include source/destination chain ID. Message for chain A is valid on chain B."},
        {"name": "fake_message_source", "difficulty": "intermediate", "desc": "Bridge does not verify the true source of a cross-chain message. Attacker forges a message from a trusted source."},
        {"name": "relayer_censorship", "difficulty": "advanced", "desc": "Single relayer controls message delivery. Can censor, delay, or reorder messages for profit."},
        {"name": "token_mapping_mismatch", "difficulty": "advanced", "desc": "Bridge maps token A on chain 1 to token B on chain 2. Mapping can be manipulated to mint wrong tokens."},
    ],
    "dex-amm-logic": [
        {"name": "no_slippage_check", "difficulty": "beginner", "desc": "Swap function has no minimum output amount parameter. Or amountOutMin is always 0. Sandwich attacks extract full value."},
        {"name": "lp_token_inflation", "difficulty": "intermediate", "desc": "First liquidity provider gets disproportionate LP tokens by manipulating the initial ratio."},
        {"name": "constant_product_rounding", "difficulty": "intermediate", "desc": "AMM constant product formula (x*y=k) rounding errors allow small profit extraction per swap."},
        {"name": "pool_reserve_desync", "difficulty": "intermediate", "desc": "Pool tracks reserves internally but actual token balance differs (due to fee-on-transfer tokens or direct sends)."},
        {"name": "tick_manipulation", "difficulty": "advanced", "desc": "Concentrated liquidity tick boundaries can be exploited. Attacker forces trades across tick boundaries for extra extraction."},
    ],
    "governance-attacks": [
        {"name": "flash_loan_vote", "difficulty": "beginner", "desc": "Voting power based on current balance, not snapshot. Flash loan tokens to pass a proposal in one transaction."},
        {"name": "proposal_griefing", "difficulty": "intermediate", "desc": "Anyone can propose. Attacker floods with proposals to exhaust voters or delay legitimate proposals past deadline."},
        {"name": "timelock_instant_execute", "difficulty": "intermediate", "desc": "Timelock delay can be set to 0 by governance. Admin proposes delay=0, waits, then executes arbitrary code instantly."},
        {"name": "vote_delegation_chain", "difficulty": "advanced", "desc": "Vote delegation creates a circular chain or concentrates voting power in unintended ways through chained delegations."},
        {"name": "quorum_manipulation", "difficulty": "advanced", "desc": "Quorum is based on total supply. Burning tokens or locking them reduces total supply, making quorum easier to reach."},
    ],
    "token-accounting": [
        {"name": "fee_on_transfer", "difficulty": "beginner", "desc": "Contract assumes transfer(100) delivers 100 tokens. Fee-on-transfer token delivers 97. Internal accounting is inflated."},
        {"name": "rebasing_incompatible", "difficulty": "intermediate", "desc": "Contract stores token amounts as fixed values. Rebasing token changes balances externally. Stored values become stale."},
        {"name": "erc777_callback", "difficulty": "intermediate", "desc": "Token is ERC777 compatible. Transfer hooks (tokensReceived) give recipient control during transfer, enabling reentrancy."},
        {"name": "decimal_assumption", "difficulty": "intermediate", "desc": "Contract assumes all tokens have 18 decimals. USDC (6), WBTC (8), and others break the math by orders of magnitude."},
        {"name": "approval_race", "difficulty": "advanced", "desc": "ERC20 approve race condition. User reduces allowance from 100 to 50, but attacker front-runs to spend 100 then 50."},
    ],
    "price-manipulation": [
        {"name": "spot_price_as_oracle", "difficulty": "beginner", "desc": "Uses AMM pool reserves ratio as price oracle. Flash loan can manipulate reserves within a single transaction."},
        {"name": "lp_token_price", "difficulty": "intermediate", "desc": "LP token price calculated from pool reserves. Attacker manipulates one reserve to inflate LP token value used as collateral."},
        {"name": "virtual_price_attack", "difficulty": "intermediate", "desc": "Curve-style virtual_price can be manipulated via reentrancy during add/remove liquidity operations."},
        {"name": "multi_pool_arbitrage", "difficulty": "advanced", "desc": "Price discrepancy between two pools exploited atomically. Protocol reads from the manipulated pool."},
        {"name": "donation_price_manipulation", "difficulty": "advanced", "desc": "Direct token transfer to a vault/pool inflates the 'price per share' or 'reserves ratio' without going through deposit logic."},
    ],
}
